

spring:
  application:
    name: 'vmall-portal'
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.42.247:8848
dubbo:
  scan:
    base-packages: com.vuuvv.vmall.services
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
server:
  port: 7001
